######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 23 20:49:34 2010
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../common

# Input
HEADERS += openthermoextension.hpp
SOURCES += openthermoextension.cpp
