######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 23 20:47:17 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../common

# Input
SOURCES += main.cpp
